<a href="https://colab.research.google.com/github/merazlab/pytorch/blob/master/conv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np


In [2]:
print(torch.__version__)


1.7.0+cu101


In [11]:
input_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)
input_2d = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype = torch.float)
input_2d_img = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]], dtype = torch.float)

In [12]:
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape


torch.Size([1, 1, 10])

# 1D_Conv

nn.Conv1d() applies 1D convolution over the input. nn.Conv1d() expects the 

 input to be of the shape ` [batch_size, input_channels, signal_length] `

## 1D_Conv_1D_Signal

In [14]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=1)
print(cnn1d_1.weight)
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

Parameter containing:
tensor([[[ 0.0509,  0.0901, -0.2756]]], requires_grad=True)
torch.Size([1, 1, 8]) 

tensor([[[-0.4782, -0.6129, -0.7475, -0.8821, -1.0167, -1.1513, -1.2860,
          -1.4206]]], grad_fn=<SqueezeBackward1>)


In [15]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=3, stride=2)
print(cnn1d_1.weight)
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

Parameter containing:
tensor([[[ 0.3151,  0.3011, -0.0425]]], requires_grad=True)
torch.Size([1, 1, 4]) 

tensor([[[0.9016, 2.0490, 3.1964, 4.3438]]], grad_fn=<SqueezeBackward1>)


In [16]:
cnn1d_1 = nn.Conv1d(in_channels=1, out_channels=5, kernel_size=3, stride=1)
print(cnn1d_1.weight)
print(cnn1d_1(input_1d).shape, "\n")
print(cnn1d_1(input_1d))

Parameter containing:
tensor([[[-0.0654,  0.4991,  0.4264]],

        [[ 0.5160, -0.2211, -0.4868]],

        [[ 0.2075,  0.3568,  0.5247]],

        [[-0.3352,  0.1799,  0.1520]],

        [[ 0.1411, -0.4305, -0.0362]]], requires_grad=True)
torch.Size([1, 5, 8]) 

tensor([[[ 1.8545,  2.7146,  3.5747,  4.4348,  5.2948,  6.1549,  7.0150,
           7.8751],
         [-1.9290, -2.1210, -2.3129, -2.5049, -2.6968, -2.8887, -3.0807,
          -3.2726],
         [ 1.9199,  3.0089,  4.0979,  5.1869,  6.2759,  7.3649,  8.4539,
           9.5429],
         [ 1.0072,  1.0039,  1.0006,  0.9974,  0.9941,  0.9908,  0.9875,
           0.9843],
         [-0.4015, -0.7271, -1.0527, -1.3784, -1.7040, -2.0296, -2.3552,
          -2.6809]]], grad_fn=<SqueezeBackward1>)


## 1D_Conv_2D_signal


In [17]:
input_2d = input_2d.unsqueeze(0)
input_2d.shape

torch.Size([1, 2, 5])

In [18]:
input_2d

tensor([[[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]])

In [19]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=1, kernel_size=3, stride=1)
print(cnn1d_5.weight)
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

Parameter containing:
tensor([[[-0.2062,  0.0005, -0.3756],
         [ 0.1928,  0.1047,  0.0198]]], requires_grad=True)
torch.Size([1, 1, 3]) 

tensor([[[ 0.4046,  0.1407, -0.1233]]], grad_fn=<SqueezeBackward1>)


In [22]:
cnn1d_5 = nn.Conv1d(in_channels=2, out_channels=5, kernel_size=3, stride=1)
print(cnn1d_5.weight)
print(cnn1d_5(input_2d).shape, "\n")
print(cnn1d_5(input_2d))

Parameter containing:
tensor([[[-0.2145, -0.0506,  0.1776],
         [-0.0154, -0.2767,  0.1374]],

        [[-0.2318,  0.1197,  0.4051],
         [-0.3108, -0.2018,  0.2985]],

        [[-0.2883, -0.1855,  0.3288],
         [ 0.3725, -0.0675, -0.0171]],

        [[-0.2086, -0.3898,  0.0302],
         [-0.2146, -0.3973, -0.2139]],

        [[ 0.0872, -0.0602, -0.2913],
         [-0.3415, -0.0425,  0.1098]]], requires_grad=True)
torch.Size([1, 5, 3]) 

tensor([[[-0.6581, -0.9002, -1.1423],
         [ 0.4314,  0.5103,  0.5893],
         [ 1.9634,  2.1064,  2.2493],
         [-6.9810, -8.3751, -9.7692],
         [-2.7112, -3.2498, -3.7883]]], grad_fn=<SqueezeBackward1>)


# 2D_Conv

nn.Conv2d() applies 2D convolution over the input.

`nn.Conv2d()` expects the input to be of the shape `[batch_size, input_channels, input_height, input_width] `

## 2D_Conv_1D_signal

In [24]:
input_1d = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype = torch.float)


In [25]:
input_1d = input_1d.unsqueeze(0).unsqueeze(0)
input_1d.shape


torch.Size([1, 1, 10])

In [27]:
cnn2d_1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=1)
print(cnn2d_1.weight)


Parameter containing:
tensor([[[[-0.1302,  0.3228,  0.2812],
          [ 0.0621, -0.0121,  0.2955],
          [ 0.2245,  0.1087,  0.1523]]]], requires_grad=True)


In [29]:
# print(cnn2d_1(input_1d).shape, "\n") #Convolution not perform because kernel size mismatch
# print(cnn2d_1(input_1d))

## 2D_Conv_2D_Signal

In [34]:
input_2d = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype = torch.float)


In [35]:
input_2d = input_2d.unsqueeze(0).unsqueeze(0)
input_2d.shape

torch.Size([1, 1, 2, 5])

In [40]:
cnn2d_1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=1)
print(cnn2d_1.weight)

Parameter containing:
tensor([[[[-0.1745, -0.0526],
          [ 0.2039,  0.4038]]]], requires_grad=True)


In [41]:
print(cnn2d_1(input_2d).shape, "\n")
print(cnn2d_1(input_2d))

torch.Size([1, 1, 1, 4]) 

tensor([[[[3.5396, 3.9201, 4.3006, 4.6810]]]], grad_fn=<ThnnConv2DBackward>)


### kernel size `[1, 2]`

In [42]:
cnn2d_1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=(1, 2), stride=1)
print(cnn2d_1.weight)

Parameter containing:
tensor([[[[-0.0626,  0.5710]]]], requires_grad=True)


In [43]:
print(cnn2d_1(input_2d).shape, "\n")
print(cnn2d_1(input_2d))

torch.Size([1, 1, 2, 4]) 

tensor([[[[0.3741, 0.8825, 1.3909, 1.8993],
          [2.9161, 3.4245, 3.9328, 4.4412]]]], grad_fn=<ThnnConv2DBackward>)


## 2D_Conv_3D_Signal

In [48]:
input_2d_img = torch.tensor([[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], [[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]], dtype = torch.float)

In [50]:
input_2d_img = input_2d_img.unsqueeze(0)
input_2d_img.shape

torch.Size([1, 3, 3, 10])