<a href="https://colab.research.google.com/github/merazlab/pytorch/blob/master/dataprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
cd /content/drive/My Drive/pytorch

/content/drive/My Drive/pytorch


In [62]:
ls


dataprocessing.ipynb  mod_01_Intro.ipnb  Untitled0.ipynb
diabetes.csv          mod_02_01.ipynb


In [0]:
import numpy as np
import torch
import torch.nn  as nn
import pandas as pd
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset

In [0]:
data = pd.read_csv("diabetes.csv")

In [0]:
x = data.iloc[:, 0:-1]
y_string = list(data.iloc[:,-1])

In [66]:
print(type(x))
print(type(y_string))

<class 'pandas.core.frame.DataFrame'>
<class 'list'>


In [67]:
print(x[:3])

   Number of times pregnant  Plasma glucose concentration  ...  Body mass index  Age
0                         6                           148  ...             33.6   50
1                         1                            85  ...             26.6   31
2                         8                           183  ...             23.3   32

[3 rows x 7 columns]


In [68]:
print(y_string)

['positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'negative', 'positive', 'negative', 'positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive', 'positive', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'positive', 'positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'negative', 'positive', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'negative', 'positive', 'negative', 'negative', 'negative', 'negative', 'ne

In [0]:
y_int = []
         
for val in y_string: 
  if val == "positive":
    y_int.append(1)
  else:
    y_int.append(0)


In [0]:
y = np.array(y_int, dtype="float64")

In [0]:
sc  = StandardScaler()

In [0]:
x = sc.fit_transform(x)

In [73]:
print(type(x))

<class 'numpy.ndarray'>


In [0]:
x= torch.tensor(x)
y = torch.tensor(y).view(-1, 1)

In [75]:
print(x.size())
print(y.size())

torch.Size([768, 7])
torch.Size([768, 1])


In [0]:
class Dataset(Dataset):
  def __init__(self, x, y):
    self.x = x
    self.y = y
  def __getitem__(self, index):
    return self.x[index], self.y[index]

  def __len__(self):
    # return len(self.y)
    return len(self.x)

In [0]:
dataset = Dataset(x, y)

In [78]:
len(dataset)

768

In [79]:
first_data = dataset[0]
feature, label = first_data
print(feature)
print(label)

tensor([ 0.6399,  0.8483,  0.1496,  0.9073, -0.6929,  0.2040,  1.4260],
       dtype=torch.float64)
tensor([1.], dtype=torch.float64)


Now Batch size concept

In [0]:
train_loder = torch.utils.data.DataLoader(dataset=dataset, batch_size=4, shuffle=True)

In [81]:
data_iter = iter(train_loder)
data_batch = next(data_iter)

feature, label = data_batch
print(feature)
print(label)

tensor([[-0.2510,  2.1941, -0.0572, -0.3473,  0.4359, -0.1387,  0.0646],
        [ 0.3430,  1.1613,  0.7700,  1.2836,  1.1305,  0.9401, -0.3608],
        [-1.1419, -0.0593, -0.2639, -0.1591,  0.1059,  0.3690, -0.8714],
        [-0.2510, -0.2471, -1.2979, -0.4727, -0.6929, -1.2175, -0.9565]],
       dtype=torch.float64)
tensor([[0.],
        [1.],
        [0.],
        [0.]], dtype=torch.float64)


In [82]:
for i, (feature, label) in enumerate(train_loder):
  print(i,  feature, label)
  if i == 2: break

0 tensor([[-0.2510,  1.1613,  0.0462,  0.5936,  2.1551,  0.4452,  0.1497],
        [-0.8449, -0.5913,  0.2530, -1.2882, -0.6929,  0.9528,  0.7453],
        [-1.1419,  1.8498,  1.0802,  0.3427,  0.0886,  0.5721,  0.1497],
        [ 0.0460, -0.1219, -0.3673, -0.5355, -0.6929, -0.2910, -0.2758]],
       dtype=torch.float64) tensor([[1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64)
1 tensor([[-0.2510,  1.1613,  0.3564,  0.9700,  1.4344, -0.0498, -0.4459],
        [ 0.6399, -1.2799,  0.5632,  0.9700, -0.6929,  0.9909, -0.4459],
        [ 1.2339,  2.1002,  0.4598, -1.2882, -0.6929,  2.0190,  0.8304],
        [ 0.3430,  0.8170,  0.3047, -1.2882, -0.6929, -0.2656, -0.4459]],
       dtype=torch.float64) tensor([[1.],
        [0.],
        [1.],
        [0.]], dtype=torch.float64)
2 tensor([[-0.8449,  0.0346, -0.2639,  0.7191,  0.6616,  0.3944, -0.2758],
        [-0.2510,  0.2224,  0.1496,  0.2800,  0.9569,  0.0517, -0.5310],
        [ 0.0460,  1.0987,  0.3047, -1.2882, -0.69

Model

Linear layer == MLP = Fcn

In [0]:
class Model(nn.Module):
  def __init__(self, input_features, output_features):
    super(Model, self).__init__()
    self.fc1 = nn.Linear(input_features, 5)
    self.fc2 = nn.Linear(5, 4)
    self.fc3 = nn.Linear(4, 3)
    self.fc4 = nn.Linear(3, output_features)
    self.sigmoid = nn.Sigmoid()
    self.tanh = nn.Tanh()

  def forward(self, x):
    out = self.fc1(x)
    out= self.tanh(out)
    out = self.fc2(out)
    out= self.tanh(out)
    out = self.fc3(out)
    out= self.tanh(out)
    out = self.fc4(out)
    out= self.sigmoid(out)
    return out


In [84]:
net = Model(7, 1)
criterion = torch.nn.BCELoss(size_average=True) # due to batch
optimizer = torch.optim.SGD(net.parameters(), lr = 0.1, momentum=0.9)


/usr/local/lib/python3.6/dist-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))


In [100]:
epochs = 200
for epoch in range(epochs):
  for inputs, labels in train_loder:
    inputs = inputs.float()
    labels = labels.float()
    # foreard
    outputs = net(inputs)
    #Loss calculation
    loss = criterion(outputs, labels)
    # print(inputs.dtype)
    # print(labels.dtype)
    # print(outputs.dtype)
    # print(loss.dtype)
    # break
    #clear gradiant buffer
    optimizer.zero_grad()
    #calculate gradiant W <<--- W - lr*gradiant
    loss.backward()
    optimizer.step()
  
  #Accuracy calculation
  outputs = (outputs > 0.5)
  # print(outputs.dtype)
  outputs = outputs.float()
  # print(outputs.dtype)
  accuracy = (outputs == labels).float().mean()
  print(accuracy.dtype)
  print("Epoch{}/{}, loss: {:.3f}, Accuracy: {:.3f}". format(epoch+1, epochs, loss, accuracy))


torch.float32
Epoch1/200, loss: 0.671, Accuracy: 0.500
torch.float32
Epoch2/200, loss: 0.161, Accuracy: 1.000
torch.float32
Epoch3/200, loss: 0.824, Accuracy: 0.500
torch.float32
Epoch4/200, loss: 0.399, Accuracy: 1.000
torch.float32
Epoch5/200, loss: 0.728, Accuracy: 0.750
torch.float32
Epoch6/200, loss: 0.577, Accuracy: 0.750
torch.float32
Epoch7/200, loss: 0.273, Accuracy: 0.750
torch.float32
Epoch8/200, loss: 0.709, Accuracy: 0.500
torch.float32
Epoch9/200, loss: 0.682, Accuracy: 0.750
torch.float32
Epoch10/200, loss: 0.661, Accuracy: 0.750
torch.float32
Epoch11/200, loss: 0.520, Accuracy: 0.750
torch.float32
Epoch12/200, loss: 0.219, Accuracy: 1.000
torch.float32
Epoch13/200, loss: 0.517, Accuracy: 0.750
torch.float32
Epoch14/200, loss: 0.307, Accuracy: 1.000
torch.float32
Epoch15/200, loss: 1.162, Accuracy: 0.250
torch.float32
Epoch16/200, loss: 0.863, Accuracy: 0.500
torch.float32
Epoch17/200, loss: 0.774, Accuracy: 0.500
torch.float32
Epoch18/200, loss: 0.266, Accuracy: 1.000
t