autograd

In [0]:
import torch

In [0]:
a = torch.randint(1, 5,(3,))
print(a)

tensor([3, 2, 1])


In [0]:
print(a.requires_grad)

False


In [0]:
b = torch.randint(1, 5,(3,), dtype=torch.int16, requires_grad=True)
print(b)

RuntimeError: ignored

In [0]:
b = torch.randint(1, 5,(3,), dtype=torch.float64, requires_grad=True) #it only support float type data 
print(b)

tensor([2., 3., 4.], dtype=torch.float64, requires_grad=True)


In [0]:
print(b.grad_fn)

None


In [0]:
y = b + 2
z = b * 2

In [0]:
print(y.grad_fn)
print(z.grad_fn)


In [0]:
a = torch.randn(2, 2)
a = a * 3
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


Exaple

In [0]:
x = torch.randint(1, 5,(3,), dtype=torch.float64, requires_grad=True) 
print(x)

tensor([1., 1., 4.], dtype=torch.float64, requires_grad=True)


In [0]:
y = torch.sum(x**2)

In [0]:
print(x)
print(y)
print(x.grad)
print(y.grad)

tensor([1., 1., 4.], dtype=torch.float64, requires_grad=True)
tensor(18., dtype=torch.float64, grad_fn=<SumBackward0>)
None
None


In [0]:
y.backward()

In [0]:
print(x)
print(y)
print(x.grad)
print(y.grad)

tensor([1., 1., 4.], dtype=torch.float64, requires_grad=True)
tensor(18., dtype=torch.float64, grad_fn=<SumBackward0>)
tensor([2., 2., 8.], dtype=torch.float64)
None


In [2]:
# Create a variable
x=torch.tensor(torch.arange(0,4), dtype=torch.float64, requires_grad=True)
print(x)

# Differentiate
torch.sum(x**2).backward()
print(x.grad)

# Differentiate again (accumulates gradient)
torch.sum(x**2).backward()
print(x.grad)

# Zero gradient before differentiating
x.grad.data.zero_()
torch.sum(x**2).backward()
print(x.grad)

tensor([0., 1., 2., 3.], dtype=torch.float64, requires_grad=True)
tensor([0., 2., 4., 6.], dtype=torch.float64)
tensor([ 0.,  4.,  8., 12.], dtype=torch.float64)
tensor([0., 2., 4., 6.], dtype=torch.float64)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


detach

detach() method, which returns a tensor with the same data but forgotten the computation history.

In [6]:
x=torch.tensor(torch.arange(0,4),dtype=torch.float64, requires_grad=True)
y=x**2
z=y**2
print(z.grad_fn)
new_z = z.detach()
print(new_z.grad_fn)

None


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


In [7]:

#You can also stop autograd from tracking history on Tensors. This concept is useful when applying Transfer Learning 
print(x.requires_grad)
print((x+10).requires_grad)

with torch.no_grad():
    print((x+10).requires_grad)

True
True
False
